:- consult(funciones).

insertar:-
mundiales_connect,
insert_team(bra, brazil, 1),
insert_team(eng, england, 4),
insert_team(uru, uruguay, 4),
insert_team(ita, italy, 4),
insert_team(crc, costa_rica, 4),
insert_team(fra, france, 5),
insert_team(sui, switzerland, 5),
insert_team(ecu, ecuador, 5),
insert_team(hon, honduras, 5),
insert_team(irn, iran, 6),
insert_team(arg, argentina, 6),
insert_team(ger, germany, 7),
insert_team(gha, ghana, 7),
insert_team(nga, nigeria, 6),
insert_team(bih, bosnia_and_herzegovina, 6),
insert_team(bel, belgium, 8),
insert_team(rus, russia, 8),
insert_team(alg, algeria, 8),
insert_team(kor, korea_republic, 8),
insert_team(por, portugal, 7),
insert_team(usa, usa, 7),
insert_team(ned, netherlands, 2),
insert_team(aus, australia, 2),
insert_team(esp, spain, 2),
insert_team(chi, chile, 2),
insert_team(cro, croatia, 1),
insert_team(cmr, cameroon, 1),
insert_team(mex, mexico, 1),
insert_team(col, colombia, 3),
insert_team(civ, ivory_coast, 3),
insert_team(gre, greece, 3),
insert_team(jpn, japan, 3),
mundiales_disconnect.
